#!/usr/bin/env python3
"""
将 shaders/ 目录下的 .vert/.frag 文件转换为 C++ 原始字符串常量头文件。

用法: python3 embed_shaders.py <shader_dir> <output_header>

生成的头文件包含如下常量（文件名转为大写 + 下划线）：
  post_process.vert  → SHADER_POST_PROCESS_VERT
  post_process.frag  → SHADER_POST_PROCESS_FRAG
  fsr_easu.frag      → SHADER_FSR_EASU_FRAG
  ...
"""

import os
import sys
import re

def filename_to_varname(filename: str) -> str:
    """post_process.frag → SHADER_POST_PROCESS_FRAG"""
    name = os.path.splitext(filename)[0] + '_' + os.path.splitext(filename)[1].lstrip('.')
    name = re.sub(r'[^a-zA-Z0-9]', '_', name)
    return 'SHADER_' + name.upper()

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <shader_dir> <output_header>", file=sys.stderr)
        sys.exit(1)

    shader_dir = sys.argv[1]
    output_path = sys.argv[2]

    # 收集所有着色器文件
    shader_files = sorted(
        f for f in os.listdir(shader_dir)
        if f.endswith(('.vert', '.frag'))
    )

    if not shader_files:
        print(f"No .vert/.frag files found in {shader_dir}", file=sys.stderr)
        sys.exit(1)

    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)

    lines = [
        '// Auto-generated by embed_shaders.py — DO NOT EDIT',
        '// Source: nativelib/src/main/cpp/shaders/',
        '#pragma once',
        '',
    ]

    for filename in shader_files:
        varname = filename_to_varname(filename)
        filepath = os.path.join(shader_dir, filename)
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()

        lines.append(f'// {filename}')
        # 注意：R"( 与 shader 第一行之间不能插入 \n，否则 #version 会被推到第 2 行
        # 触发 GLSL ES 严格错误："P0005: #version must be on the first line"
        lines.append(f'static const char* {varname} = R"(' + content.rstrip() + ')";')
        lines.append('')

    # 写入前检查内容是否变化，避免不必要的重编译
    new_content = '\n'.join(lines) + '\n'
    if os.path.exists(output_path):
        with open(output_path, 'r', encoding='utf-8') as f:
            if f.read() == new_content:
                return  # 无变化，跳过

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"Generated {output_path} with {len(shader_files)} shaders:")
    for fn in shader_files:
        print(f"  {filename_to_varname(fn)} ← {fn}")

if __name__ == '__main__':
    main()
